#!/bin/bash

# Bspwm configurations
bspc monitor -d '1' '2' '3' '4' '5' '6'
bspc config focus_follows_pointer true
bspc config top_padding 32
bspc config border_width 4
bspc config window_gap 8
bspc config focused_border_color "#98c379"
bspc config normal_border_color "#3e4452"
bspc config active_border_color "#e06c75"
bspc config presel_feedback_color "#56b6c2"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

# Window rules
bspc rule -r *:*
bspc rule -a kitty desktop='^1' follow=on focus=on
bspc rule -a Firefox-esr desktop='^2' follow=on focus=on
bspc rule -a Transmission-gtk desktop='^2' follow=on focus=on
bspc rule -a Org.gnome.Nautilus desktop='^3' follow=on focus=on
bspc rule -a File-roller desktop='^3' follow=on focus=on
bspc rule -a libreoffice desktop='^4' follow=on focus=on
bspc rule -a *:soffice desktop='^4' follow=on focus=on
bspc rule -a Soffice desktop='^4' follow=on focus=on
bspc rule -a libreoffice-writer desktop='^4' follow=on focus=on
bspc rule -a libreoffice-calc desktop='^4' follow=on focus=on
bspc rule -a libreoffice-impress desktop='^4' follow=on focus=on
bspc rule -a Geany desktop='^4' follow=on focus=on
bspc rule -a Evince desktop='^4' follow=on focus=on
bspc rule -a Gimp desktop='^5' follow=on focus=on
bspc rule -a Gimp-2.10 desktop='^5' follow=on focus=on
bspc rule -a Inkscape desktop='^5' follow=on focus=on
bspc rule -a Pavucontrol desktop='^6' follow=on focus=on
bspc rule -a System-config-printer.py desktop='^6' follow=on focus=on
bspc rule -a Lxappearance desktop='^6' follow=on focus=on
bspc rule -a Gparted desktop='^3' follow=on focus=on
bspc rule -a Audacious state=floating follow=on focus=on
bspc rule -a Firefox:Places state=floating follow=on focus=on
bspc rule -a Viewnior state=floating follow=on focus=on
bspc rule -a mpv state=floating follow=on focus=on

# Bspwm Autostart
pkill sxhkd
pkill polybar
sxhkd &
polybar top &
